### ISSUE TITLE
Line limits units (`rateA`)

### ISSUE THREAD

**Issue by jacob-roth** [power-grid-lib/pglib-opf#27]
Hi, first, thanks for your work aggregating and building this library!

I'm trying to use the 1354pegase case and am implementing my own simplified opf model where I want to impose line current constraints for line `l = (i,j)` according to
```
(|y_ij| |V_i - V_j|)^2 <= rhs
```
for `V_i`, `V_j` the complex voltages at buses `i` and `j` and `|y_ij|` is the magnitude of the `(i,j)` element of the admittance matrix. (Btw, I'm ignoring tap adjustments now...)

However, I'm not sure what the units of the `rhs` should be from the `pglib` case. According to Table V of the report (https://arxiv.org/abs/1908.02788), it seems that `rateA` is a thermal limit that was determined by the `TL-UB` method from Section V.B.2. Does this mean that the `rateA` is already normalized by baseMVA and given in p.u. form? Or should I divide `rateA` by 100 to get the p.u. (and then square it to set the value of the `rhs`).

Thanks!

**Comment by ccoffrin** [comment]
I am glad to hear that you are finding the library useful!  The Matpower user manual is where you will find details about the data model.

To answer this specific question, the "rate" values are given in MVA.  You need to divide them by the `baseMVA` parameter to get them into p.u. for posing a model in consistent units.  In these cases `baseMVA` is alway 100.0.
