### ISSUE TITLE
Help In SDP-Relaxation method for solving OPF Problem

### ISSUE THREAD

**Issue by 12146** [power-grid-lib/pglib-opf#31]
Hello Sir,
i came to  know about you from your videos of Convex Relaxations in Youtube...
Sir i need help from you, i am stuck in my project work....i am trying to find an optimze a system 3m9b for test....

and i wrote the optimization problem like this....
for i=1:1
cvx_begin
cvx_solver sedumi
                       
variables u(npv,1)
variable W(2*n,2*n) symmetric
summ=trace(YYreal(:,:,1)*W);
for i=2:n
    summ=summ+trace(YYreal(:,:,i)*W);
end
for i=1:npv
u(i,1)==trace(YYreal(:,:,i+npq)*W);    
(This u contais the PV buses active power generation...(whose optimal value has to be found))
end
 minimize(w*(sum(u)+trace(YYreal(:,:,n)*W)))

subject to
       for i=1:npq                (this  are equality constraints "calculated active power=specified active power" for pv&pq buses)
           trace(YYreal(:,:,i)*W)-(Pg(i,1)-Pl(i,1))==0;
           trace(YYreal(:,:,i)*W)-(Pg(i,1)-Pl(i,1))==0;
       end
       for i=1:npv
                               (this bounds i thought to apply after getting a local optimal solution from Newtons Method)
    trace(YYreal(:,:,i+npq)*W)+Pl(i+npq,1)>=-0.2
  trace(YYreal(:,:,i+npq)*W)+Pl(i+npq,1)<=3
       end

for i=1:npq    (this are equality  constraints "calculated reactive power=specified reactive power" for only pq buses)
           trace(YYimag(:,:,i)*W)-(Qg(i,1)-Ql(i,1))==0;
           trace(YYimag(:,:,i)*W)-(Qg(i,1)-Ql(i,1))==0;
end

  W==semidefinite(2*n);
       W>=0;
   cvx_end
   w=w+1
   for i=1:npv
       Pg(i+npq,1)=trace(YYreal(:,:,i+npq)*W)+Pl(i+npq,1);
   end
end

Sir,
in the paper it is "Zero Duality Gap In Optimal Power Flow" that rank of W matrix variable should come=1 when the duality gap is "0". and for that we applied weight method.(w is the weight)..

Sir..
for some values of w i get solution as 'NAN'.
and for some i get an optimal solution...but the 'W matrix' never comes of rank 1...

i dont know where i am going wrong...but please help me with this....

**Comment by ccoffrin** [comment]
Hi @12146, this repo is a collection of datasets and is not the right place to seek help on algorithm implementations.  It looks like you are using CVX in Matlab so I would recommend that you direct this question through the CVX forums.

I maintain a number of implementations in Julia as part of PowerModels.jl.  If you have questions about that platform you can use https://discourse.julialang.org/

Good luck.
