### ISSUE TITLE
Move to TYP folder

### ISSUE THREAD

**Issue by yasirroni** [power-grid-lib/pglib-opf#38]
Dear dr @rdzman, I propose that we move files to Typical Operating Conditions (TYP) folder to make the code structure more consistent.

I can make a PR if you agreed,

Thanks,

**Comment by ccoffrin** [comment]
Hi @yasirroni, thanks for your interest in PGLib-OPF.

The TYP cases are special in that they are the base case (or closest to that) of the source data that is used to build PGLib.  the API and SAD variants are derivatives of this base case.  This is the reason why TYP is in the root directory and the other two have dedicated sub directories.

Given that the current organization has been working well for many years, I don't see a compelling reason to change it.
