### ISSUE TITLE
context for _GOC cases?

### ISSUE THREAD

**Issue by frederikgeth** [power-grid-lib/pglib-opf#44]
I'm looking for more information on the _goc cases, but the link in reference 45 in the arxiv report appears broken. 

I'm curious if there is more background on the _goc cases surviving elsewhere? They seem to have some unique features when it comes to the structure of the mesh of the network. I would love to understand if this has anything to do with real world networks, or if it may be an artefact of a topology which was generated through a statistical model.

Thanks!

**Comment by ccoffrin** [comment]
This link is currently working, https://gocompetition.energy.gov/

Look at the header of a network file for more information about how it was
generated.  Many different teams and methods contributed to the goc cases.

**Comment by frederikgeth** [comment]
Great thanks!

For anyone who ends up here in the future, the tips led me to https://gocompetition.energy.gov/challenges/22/datasets and https://egriddata.org/dataset/sdet-tool. The SDET tool documentation seems to suggest that it wouldn't modify the topology of lines/transformers, just anonymize.

**Comment by ccoffrin** [comment]
I have a vague recollection of some odd topological features int he SDET data, but I don't recall the details.

It seems resolved, shall we close this issue?

**Comment by frederikgeth** [comment]
Yeah, fine by me to close it. If anyone has more background on the origin of the cases, I'm curious to learn more.

**Comment by frederikgeth** [comment]
Yeah, fine by me to close it. If anyone has more background on the origin of the cases, I'm curious to learn more.
